name: look_up_demo_app
description: "A new Flutter demo app for Loop Up task"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

scripts:
  build: dart run build_runner build --delete-conflicting-outputs

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  get_it: ^7.6.4
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  share_plus: ^7.2.1
  sqflite: ^2.3.0
  path: ^1.8.3
  mockito: ^5.4.4
  confetti: ^0.7.0
  firebase_storage: ^11.5.6
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo_letter/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
